kind: Deployment
apiVersion: apps/v1
metadata:
  name: url-shortener
spec:
  replicas: 1
  selector:
    matchLabels:
      app: url-shortener-app
  template:
    metadata:
      labels:
        app: url-shortener-app
    spec:
      containers:
        - name: url-shortener
          image: url-shortener-image:latest
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            requests:
              memory: "180Mi"
              cpu: "10m"
---
kind: Service
apiVersion: v1
metadata:
  name: url-shortener-svc
spec:
  ports:
    - name: http-8080
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: url-shortener-app